from enum import Enum


class AgentType(str, Enum):
    """Enum for different types of agents."""

    SEARCH_QUERY = "SEARCH_QUERY"
    SUFFICIENT_DETAIL = "SUFFICIENT_DETAIL"
    CONVERSATION_ENRICHMENT = "CONVERSATION_ENRICHMENT"
    CONVERSATION_SATURATION = "CONVERSATION_SATURATION"
    GREETING_DETECTION = "GREETING_DETECTION"
    PRODUCT_REFERENCE = "PRODUCT_REFERENCE"
    USER_PROFILE_EXTRACTION = "USER_PROFILE_EXTRACTION"
